---
# tasks file for dokuwikicmdb
- name: Gather package facts if not already gathered
  ansible.builtin.package_facts:
    manager: auto

- name: Gather service facts if not already gathered
  ansible.builtin.service_facts:

- name: Include Zabbix tasks
  ansible.builtin.include_tasks: zabbix.yml
  when: check_zabbix == "yes"

- name: Include Wazuh tasks
  ansible.builtin.include_tasks: wazuh.yml
  when: check_wazuh == "yes"

- name: Include Rsyslog tasks
  ansible.builtin.include_tasks: rsyslog.yml
  when: check_rsyslog == "yes"
